#!/usr/bin/env bash
cat << EOF | kubectl apply -f -
kind: Pod
apiVersion: v1
metadata:
  name: debugger-pod
  labels:
    app: debugger-pod
spec:
  containers:
  - name: debugger
    image: yngvark/linuxtools
EOF

sleep 3

kubectl exec -it debugger-pod -- bash && (kubectl delete pod debugger-pod || true)
