apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
spec:
  rules:
    - host: {{ .Values.ingress.url }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}
              servicePort: {{ .Values.service.port }}
    - host: printheaders.api-test.oslo.kommune.no
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}
              servicePort: {{ .Values.service.port }}
    - host: printheaders.api-systest.oslo.kommune.no
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}
              servicePort: {{ .Values.service.port }}
  tls:
    - hosts:
        - {{ .Values.ingress.url }}
        - printheaders.api-test.oslo.kommune.no
        - printheaders.api-systest.oslo.kommune.no
