apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.pod.port }}
  selector:
    app: {{ .Release.Name }}
  type: ClusterIP
